# Generated by Django 3.2 on 2024-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mood', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('imdb_rating', models.FloatField()),
            ],
        ),
    ]
